<a href="https://colab.research.google.com/github/Vidikkk/NM_dz/blob/main/%D0%BB%D0%B14_%D0%9B%D0%B0%D0%BD%D0%BE%D0%B2%D0%B5%D0%BD%D0%BA%D0%BE_%D0%9E%D0%BB%D0%B5%D0%B3_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лановенко Олег
ФІТ 2-10
варіант 16
був на парі

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
matrix = np.random.randint(1, 6, size=(3,3))

matrix

array([[3, 3, 4],
       [5, 1, 5],
       [4, 1, 2]])

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(24.999999999999986)

In [ ]:
product = np.prod(matrix)
product

np.int64(7200)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1 * prod_2 * prod_3

np.int64(7200)

In [ ]:
sum_1 = np.sum(matrix)

sum_1

np.int64(28)

In [ ]:
np.max(matrix)

np.int64(5)

In [ ]:
np.min(matrix)

np.int64(1)

In [ ]:
np.mean(matrix)


np.float64(3.111111111111111)

In [ ]:
np.sqrt(matrix)

array([[1.73205081, 1.73205081, 2.        ],
       [2.23606798, 1.        , 2.23606798],
       [2.        , 1.        , 1.41421356]])

In [ ]:
np.sum(matrix, axis = 1).reshape(-1,1)

array([[10],
       [11],
       [ 7]])

In [ ]:
vector = np.random.randint(0, 10, size = 25)

print(vector)

[1 4 7 5 6 3 3 8 4 3 9 1 1 2 5 5 5 9 1 6 3 0 8 9 3]


In [ ]:
sorted_vector = np.sort(vector[::-1])
sorted_vector

array([0, 1, 1, 1, 1, 2, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 6, 6, 7, 8, 8,
       9, 9, 9])

In [37]:
a = np.array([[1, 1, -1], [3, -1, 2], [4, 4, -3]])
b = np.array([-2, 9, -5])

x = np.linalg.solve(a, b)
print('Вбудована функція', x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1)

Вбудована функція [ 1. -0.  3.]
Матричний метод [1. 0. 3.]


In [38]:
# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        #print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions
# Виклик функцій для розв'язання системи
print(kramer(a, b))

Solving a system of linear algebraic equations by Cramer's method:
[np.float64(1.0), np.float64(-0.0), np.float64(3.0)]
